import { getBranches, getProducts, setData, removeData, getOnce, pushData, atomicStock, updateData, stockForBranch } from './store.js';
import { escapeHTML, formObject, uid, number, toArray, dateTime } from './utils.js';
import { audit } from './audit.js';

export async function renderBranches(ctx){let branches=await getBranches();const draw=()=>{ctx.host.innerHTML=`<article class="card"><div class="toolbar"><div><h2>Data Cabang</h2><p class="muted">Pilih cabang dari bagian atas aplikasi untuk berpindah.</p></div><button id="addBranch" class="primary-button">+ Cabang</button></div><div class="grid three">${branches.map(b=>`<div class="card"><span class="badge">${escapeHTML(b.code||'CAB')}</span><h3 style="margin-top:12px">${escapeHTML(b.name)}</h3><p class="muted">${escapeHTML(b.address||'-')}<br>${escapeHTML(b.phone||'')}</p><div class="toolbar-group"><button class="secondary-button" data-branch-edit="${b.id}">Edit</button><button class="danger-button" data-branch-delete="${b.id}">Hapus</button></div></div>`).join('')}</div></article>`;document.querySelector('#addBranch').onclick=()=>branchForm(ctx,null,async b=>{await setData(`branches/${b.id}`,b);branches=await getBranches();draw();window.dispatchEvent(new Event('aya-branches-changed'))});ctx.host.onclick=async e=>{const edit=e.target.closest('[data-branch-edit]'),del=e.target.closest('[data-branch-delete]');if(edit)return branchForm(ctx,branches.find(b=>b.id===edit.dataset.branchEdit),async b=>{await setData(`branches/${b.id}`,b);branches=await getBranches();draw();window.dispatchEvent(new Event('aya-branches-changed'))});if(del&&confirm('Nonaktifkan cabang? Data transaksi dan cabang lama tidak dihapus.')){const old=branches.find(b=>b.id===del.dataset.branchDelete);await setData(`branches/${old.id}`,{...old,active:false,updatedAt:Date.now()});branches=branches.filter(b=>b.id!==del.dataset.branchDelete);draw();window.dispatchEvent(new Event('aya-branches-changed'))}}};draw()}
function branchForm(ctx,b,onSave){b=b||{};ctx.dialog(b.id?'Edit Cabang':'Tambah Cabang',`<form id="branchForm" class="form-grid"><label>Nama Cabang<input name="name" required value="${escapeHTML(b.name||'')}"></label><label>Kode Cabang<input name="code" maxlength="5" required value="${escapeHTML(b.code||'')}"></label><label class="full">Alamat<input name="address" value="${escapeHTML(b.address||'')}"></label><label>No. WA<input name="phone" value="${escapeHTML(b.phone||'')}"></label><label>Status<select name="active"><option value="true">Aktif</option><option value="false" ${b.active===false?'selected':''}>Nonaktif</option></select></label></form>`,`<button value="cancel" class="secondary-button">Batal</button><button id="saveBranch" class="primary-button">Simpan</button>`);document.querySelector('#saveBranch').onclick=async e=>{e.preventDefault();const f=document.querySelector('#branchForm');if(!f.reportValidity())return;const raw=formObject(f),id=b.id||raw.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||uid('branch');await onSave({...b,...raw,id,active:raw.active==='true',updatedAt:Date.now()});document.querySelector('#appDialog').close();ctx.notify('Cabang disimpan')}}

export async function renderTransfers(ctx){const [branches,products,raw]=await Promise.all([getBranches(),getProducts(),getOnce('stockTransfers')]);let transfers=toArray(raw).sort((a,b)=>b.createdAt-a.createdAt);const draw=()=>{ctx.host.innerHTML=`<article class="card"><div class="toolbar"><div><h2>Transfer Stok Antar Cabang</h2><p class="muted">Alur: dibuat → disetujui → diterima.</p></div><button id="newTransfer" class="primary-button">+ Transfer</button></div><div class="table-wrap"><table><thead><tr><th>Waktu</th><th>Barang</th><th>Dari → Tujuan</th><th>Qty</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${transfers.map(t=>`<tr><td>${dateTime(t.createdAt)}</td><td>${escapeHTML(t.productName)}</td><td>${escapeHTML(t.fromName)} → ${escapeHTML(t.toName)}</td><td>${t.qty}</td><td><span class="status ${t.status==='received'?'success':t.status==='approved'?'warning':''}">${escapeHTML(t.status)}</span></td><td>${t.status==='pending'&&['owner','supervisor'].includes(ctx.user.role)?`<button class="secondary-button" data-approve="${t.id}">Setujui</button>`:''}${t.status==='approved'?`<button class="primary-button" data-receive="${t.id}">Barang Diterima</button>`:''}</td></tr>`).join('')||'<tr><td colspan="6">Belum ada transfer.</td></tr>'}</tbody></table></div></article>`;document.querySelector('#newTransfer').onclick=()=>transferForm(ctx,branches,products,async t=>{const r=await pushData('stockTransfers',t);transfers.unshift({...t,id:r.key});draw()});ctx.host.querySelector('tbody').onclick=async e=>{const approve=e.target.closest('[data-approve]'),receive=e.target.closest('[data-receive]');if(approve){const t=transfers.find(x=>x.id===approve.dataset.approve);await updateData(`stockTransfers/${t.id}`,{status:'approved',approvedAt:Date.now(),approvedBy:ctx.user.name});t.status='approved';draw();await audit('APPROVE','STOCK_TRANSFER',{id:t.id})}if(receive){const t=transfers.find(x=>x.id===receive.dataset.receive);await atomicStock(t.productId,-number(t.qty),t.fromId);await atomicStock(t.productId,number(t.qty),t.toId);await updateData(`stockTransfers/${t.id}`,{status:'received',receivedAt:Date.now(),receivedBy:ctx.user.name});t.status='received';draw();ctx.notify('Transfer diterima; stok cabang asal dan tujuan diperbarui')}}};draw()}
function transferForm(ctx,branches,products,onSave){
  const branchOptions=branches.map(b=>`<option value="${b.id}">${escapeHTML(b.name)}</option>`).join('');
  ctx.dialog('Transfer Stok',`<form id="transferForm" class="form-grid">
    <label>Dari Cabang<select name="fromId">${branchOptions}</select></label>
    <label>Ke Cabang<select name="toId">${branchOptions}</select></label>
    <label class="full">Barang<select name="productId"></select></label>
    <label>Jumlah<input name="qty" type="number" min="1" required></label>
    <label>Keterangan<input name="notes"></label>
    <p id="sourceStockHint" class="muted full"></p>
  </form>`,`<button value="cancel" class="secondary-button">Batal</button><button id="saveTransfer" class="primary-button">Ajukan</button>`);
  const form=document.querySelector('#transferForm'),fromSelect=form.elements.fromId,productSelect=form.elements.productId,hint=document.querySelector('#sourceStockHint');
  const refreshProducts=()=>{
    const fromId=fromSelect.value;
    productSelect.innerHTML=products.map(p=>`<option value="${p.id}">${escapeHTML(p.name)} (stok ${stockForBranch(p,fromId)})</option>`).join('');
    const selected=products.find(p=>p.id===productSelect.value);
    hint.textContent=selected?`Stok tersedia di cabang asal: ${stockForBranch(selected,fromId)} ${selected.unit||'pcs'}`:'';
  };
  fromSelect.onchange=refreshProducts;productSelect.onchange=refreshProducts;refreshProducts();
  document.querySelector('#saveTransfer').onclick=async e=>{
    e.preventDefault();if(!form.reportValidity())return;
    const r=formObject(form);if(r.fromId===r.toId)return ctx.notify('Cabang asal dan tujuan harus berbeda','error');
    const p=products.find(x=>x.id===r.productId),from=branches.find(x=>x.id===r.fromId),to=branches.find(x=>x.id===r.toId),qty=number(r.qty),available=stockForBranch(p,r.fromId);
    if(qty>available)return ctx.notify(`Stok cabang asal hanya ${available} ${p.unit||'pcs'}`,'error');
    await onSave({...r,qty,productName:p.name,fromName:from.name,toName:to.name,status:'pending',requestedBy:ctx.user.name,createdAt:Date.now()});
    document.querySelector('#appDialog').close();ctx.notify('Transfer diajukan');
  };
}
