import { getProducts, saveProduct, setData, removeData, getOnce, pushData } from './store.js';
import { rupiah, escapeHTML, formObject, uid, number, csvCell, download, toArray } from './utils.js';
import { audit } from './audit.js';
import { printLabel } from './print.js';

export async function renderMaster(ctx){
  let products=(await getProducts()).filter(p=>p.active!==false);
  const draw=()=>{ctx.host.innerHTML=`<article class="card"><div class="toolbar"><div class="toolbar-group"><input id="masterSearch" placeholder="Cari barang, kode, barcode…"><select id="masterCategory"><option>Semua</option>${[...new Set(products.map(p=>p.category))].map(c=>`<option>${escapeHTML(c)}</option>`).join('')}</select></div><div class="toolbar-group"><button id="exportProducts" class="secondary-button">Export CSV</button><label class="secondary-button" style="display:inline-flex;cursor:pointer">Import CSV<input id="importProducts" type="file" accept=".csv" hidden></label><button id="addProduct" class="primary-button">+ Barang</button></div></div><div class="table-wrap"><table><thead><tr><th>Barang</th><th>Kategori</th><th>Barcode</th><th>Harga Beli</th><th>Harga Ecer</th><th>Grosir</th><th>Stok</th><th>Aksi</th></tr></thead><tbody id="productRows"></tbody></table></div></article>`;filter();bind()};
  const filter=()=>{const q=(document.querySelector('#masterSearch')?.value||'').toLowerCase(),cat=document.querySelector('#masterCategory')?.value||'Semua';const rows=products.filter(p=>(cat==='Semua'||p.category===cat)&&(`${p.name} ${p.barcode} ${p.id}`.toLowerCase().includes(q)));document.querySelector('#productRows').innerHTML=rows.map(p=>`<tr><td><strong>${escapeHTML(p.name)}</strong><br><small class="muted">${escapeHTML(p.unit)} · ${escapeHTML(p.source||'database')}</small></td><td>${escapeHTML(p.category)}</td><td>${escapeHTML(p.barcode||'-')}</td><td>${rupiah(p.cost)} / ${escapeHTML(p.unit)}<br><small class="muted">${rupiah(p.cartonCost||0)} / ${escapeHTML(p.largeUnit||'satuan besar')} · isi ${p.packSize||1}</small></td><td>${rupiah(p.price)}</td><td>${rupiah(p.wholesalePrice)}</td><td><span class="status ${Number(p.stock)<=Number(p.minStock)?'danger':'success'}">${p.stock} / min ${p.minStock}</span></td><td class="nowrap"><button class="icon-button" data-product-label="${p.id}" title="Cetak label">🏷️</button><button class="icon-button" data-product-edit="${p.id}">✏️</button><button class="icon-button" data-product-delete="${p.id}">🗑️</button></td></tr>`).join('')||'<tr><td colspan="8">Belum ada data barang.</td></tr>'};
  const bind=()=>{document.querySelector('#masterSearch').oninput=filter;document.querySelector('#masterCategory').onchange=filter;document.querySelector('#addProduct').onclick=()=>productForm(ctx,null,async p=>{await saveProduct(p);products=(await getProducts()).filter(p=>p.active!==false);draw()});document.querySelector('#productRows').onclick=async e=>{const edit=e.target.closest('[data-product-edit]'),del=e.target.closest('[data-product-delete]'),label=e.target.closest('[data-product-label]');if(label)return printLabel(products.find(p=>p.id===label.dataset.productLabel));if(edit)return productForm(ctx,products.find(p=>p.id===edit.dataset.productEdit),async p=>{await saveProduct(p);await audit('UPDATE','MASTER_PRODUCT',{id:p.id});products=(await getProducts()).filter(p=>p.active!==false);draw()});if(del&&confirm('Nonaktifkan barang ini? Data lama tidak akan dihapus.')){const old=products.find(p=>p.id===del.dataset.productDelete);await saveProduct({...old,active:false});products=products.filter(p=>p.id!==del.dataset.productDelete);draw()}};document.querySelector('#exportProducts').onclick=()=>{const headers=['id','name','category','barcode','cost','price','wholesalePrice','resellerPrice','stock','minStock','unit'];const csv=[headers.join(','),...products.map(p=>headers.map(h=>csvCell(p[h])).join(','))].join('\n');download('master-barang.csv',csv,'text/csv')};document.querySelector('#importProducts').onchange=e=>importCSV(e.target.files[0],async rows=>{for(const row of rows){const id=row.id||uid('product');await saveProduct(normalizeRow({...row,id}))}products=(await getProducts()).filter(p=>p.active!==false);draw();ctx.notify(`${rows.length} barang diimpor`)})};
  draw();
}
function normalizeRow(p){return {...p,id:p.id||uid('product'),name:p.name||'Barang baru',category:p.category||'Lainnya',barcode:p.barcode||'',cost:number(p.cost),price:number(p.price),wholesalePrice:number(p.wholesalePrice||p.price),resellerPrice:number(p.resellerPrice||p.price),stock:number(p.stock),minStock:p.minStock===undefined||p.minStock===''?5:number(p.minStock),unit:p.unit||'pcs',active:p.active!==false,updatedAt:Date.now()}}
function productForm(ctx,p,onSave){
  p=p||{};
  ctx.dialog(p.id?'Edit Barang':'Tambah Barang',`
    <form id="productForm" class="form-grid">
      <label>Nama Barang<input name="name" required value="${escapeHTML(p.name||'')}"></label>
      <label>Kategori<input name="category" required value="${escapeHTML(p.category||'')}"></label>
      <label>Kode / Barcode<input name="barcode" value="${escapeHTML(p.barcode||'')}"></label>
      <label>Satuan Kecil<input name="unit" value="${escapeHTML(p.unit||'pcs')}"></label>
      <label>Harga Beli Satuan Besar<input id="productCartonCost" name="cartonCost" inputmode="numeric" value="${p.cartonCost||0}"></label>
      <label>Isi per Satuan Besar (Jumlah Satuan Kecil)<input id="productPackSize" name="packSize" inputmode="numeric" value="${p.packSize||1}"></label>
      <label>Harga Beli Satuan Kecil<input id="productUnitCost" name="cost" inputmode="numeric" value="${p.cost||0}"></label>
      <label>Harga Jual Ecer<input name="price" inputmode="numeric" required value="${p.price||0}"></label>
      <p id="productCostHint" class="muted full" style="margin:0">Harga beli satuan kecil dihitung otomatis dari harga satuan besar ÷ isi.</p>
      <label>Harga Grosir<input name="wholesalePrice" inputmode="numeric" value="${p.wholesalePrice||p.price||0}"></label>
      <label>Harga Reseller<input name="resellerPrice" inputmode="numeric" value="${p.resellerPrice||p.price||0}"></label>
      <label>Stok<input name="stock" inputmode="numeric" value="${p.stock||0}"></label>
      <label>Stok Minimum<input name="minStock" inputmode="numeric" value="${p.minStock??5}"></label>
      <label class="full">Komposisi / Bahan (satu baris per bahan)<textarea name="ingredientsText">${escapeHTML((p.ingredients||[]).map(i=>typeof i==='string'?i:`${i.name||''}|${i.qty||''}|${i.cost||''}`).join('\n'))}</textarea></label>
    </form>`,
    `<button value="cancel" class="secondary-button">Batal</button><button id="saveProduct" value="default" class="primary-button">Simpan</button>`
  );
  const cartonInput=document.querySelector('#productCartonCost');
  const packInput=document.querySelector('#productPackSize');
  const unitCostInput=document.querySelector('#productUnitCost');
  const costHint=document.querySelector('#productCostHint');
  const recalculateCost=()=>{
    const carton=number(cartonInput.value),pack=Math.max(1,number(packInput.value));
    if(carton>0){const unitCost=Math.round(carton/pack);unitCostInput.value=unitCost;costHint.textContent=`Perhitungan: ${rupiah(carton)} ÷ ${pack} = ${rupiah(unitCost)} per satuan kecil.`}
    else costHint.textContent='Isi harga beli satuan besar untuk menghitung harga beli satuan kecil secara otomatis.';
  };
  cartonInput.oninput=recalculateCost;packInput.oninput=recalculateCost;
  if(number(cartonInput.value)>0)recalculateCost();
  document.querySelector('#saveProduct').onclick=async e=>{
    e.preventDefault();
    const form=document.querySelector('#productForm');if(!form.reportValidity())return;
    const raw=formObject(form),pack=Math.max(1,number(raw.packSize)),carton=number(raw.cartonCost),derivedCost=carton>0?Math.round(carton/pack):number(raw.cost),ingredients=raw.ingredientsText.split('\n').filter(Boolean).map(line=>{const [name,qty,cost]=line.split('|');return{name:name.trim(),qty:number(qty),cost:number(cost)}});
    const item=normalizeRow({...p,...raw,id:p.id||uid('product'),cost:derivedCost,cartonCost:carton,packSize:pack,ingredients});
    await onSave(item);document.querySelector('#appDialog').close();ctx.notify('Data barang disimpan');
  };
}
async function importCSV(file,done){if(!file)return;const text=await file.text();const lines=text.split(/\r?\n/).filter(Boolean),headers=parseLine(lines.shift());const rows=lines.map(line=>Object.fromEntries(parseLine(line).map((v,i)=>[headers[i],v])));await done(rows)}
function parseLine(line){const out=[];let cur='',quote=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'){cur+='"';i++}else if(c==='"')quote=!quote;else if(c===','&&!quote){out.push(cur);cur=''}else cur+=c}out.push(cur);return out}

const directoryConfig={customers:{title:'Data Pelanggan',nameLabel:'Nama Pelanggan'},suppliers:{title:'Data Supplier',nameLabel:'Nama Supplier'},consignments:{title:'Barang Titipan',nameLabel:'Pemilik / Supplier'},inventory:{title:'Inventaris Cabang',nameLabel:'Nama Alat / Barang'}};
export async function renderDirectory(ctx,type){const cfg=directoryConfig[type],path=type==='inventory'?`inventory/${ctx.branch.id}`:type;let rows=toArray(await getOnce(path)).filter(r=>r.active!==false);const draw=()=>{ctx.host.innerHTML=`<article class="card"><div class="toolbar"><div><h2>${cfg.title}</h2><p class="muted">Tersimpan dan dapat dilacak riwayatnya.</p></div><button id="addRow" class="primary-button">+ Tambah</button></div><div class="table-wrap"><table><thead><tr><th>Nama</th><th>Kontak / Kode</th><th>Alamat / Keterangan</th><th>Nilai</th><th>Aksi</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${escapeHTML(r.name)}</strong></td><td>${escapeHTML(r.phone||r.code||'-')}</td><td>${escapeHTML(r.address||r.notes||'-')}</td><td>${rupiah(r.balance||r.total||r.purchasePrice||0)}</td><td><button class="icon-button" data-edit="${r.id}">✏️</button><button class="icon-button" data-delete="${r.id}">🗑️</button></td></tr>`).join('')||'<tr><td colspan="5">Belum ada data.</td></tr>'}</tbody></table></div></article>`;document.querySelector('#addRow').onclick=()=>directoryForm(ctx,cfg,null,async item=>{const res=await pushData(path,item);rows.push({...item,id:res.key});draw()});ctx.host.querySelector('tbody').onclick=async e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit){const old=rows.find(r=>r.id===edit.dataset.edit);directoryForm(ctx,cfg,old,async item=>{await setData(`${path}/${old.id}`,item);rows=rows.map(r=>r.id===old.id?{...item,id:old.id}:r);draw()})}if(del&&confirm('Nonaktifkan data ini? Data lama tidak akan dihapus.')){const old=rows.find(r=>r.id===del.dataset.delete);await setData(`${path}/${old.id}`,{...old,active:false,updatedAt:Date.now()});rows=rows.filter(r=>r.id!==del.dataset.delete);draw()}}};draw()}
function directoryForm(ctx,cfg,row,onSave){row=row||{};ctx.dialog(row.id?'Edit Data':'Tambah Data',`<form id="directoryForm" class="form-grid"><label>${cfg.nameLabel}<input name="name" required value="${escapeHTML(row.name||'')}"></label><label>Contact Person / Kode<input name="contact" value="${escapeHTML(row.contact||row.code||'')}"></label><label>No. WA<input name="phone" value="${escapeHTML(row.phone||'')}"></label><label>Alamat<input name="address" value="${escapeHTML(row.address||'')}"></label><label>Saldo Hutang/Piutang/Nilai<input name="balance" inputmode="numeric" value="${row.balance||row.total||0}"></label><label>Tanggal<input name="date" type="date" value="${row.date||new Date().toISOString().slice(0,10)}"></label><label class="full">Keterangan<textarea name="notes">${escapeHTML(row.notes||'')}</textarea></label></form>`,`<button value="cancel" class="secondary-button">Batal</button><button id="saveDirectory" class="primary-button">Simpan</button>`);document.querySelector('#saveDirectory').onclick=async e=>{e.preventDefault();const f=document.querySelector('#directoryForm');if(!f.reportValidity())return;const raw=formObject(f);await onSave({...row,...raw,balance:number(raw.balance),updatedAt:Date.now()});document.querySelector('#appDialog').close();ctx.notify('Data tersimpan')}}
