import { rupiah, escapeHTML, download } from './utils.js';

function settings(){return JSON.parse(localStorage.getItem('aya.settings')||'{}')}
export function receiptHTML(sale){
  const s=settings();const rows=(sale.items||[]).map(i=>`<tr><td>${escapeHTML(i.name)}<br><small>${i.qty} × ${rupiah(i.price)}</small></td><td>${rupiah(i.qty*i.price)}</td></tr>`).join('');
  return `<!doctype html><html><head><meta charset="utf-8"><title>Nota ${sale.invoice}</title><style>@page{size:58mm auto;margin:2mm}body{width:54mm;margin:0;font:11px monospace;color:#000}.c{text-align:center}.r{text-align:right}h2,p{margin:3px 0}table{width:100%;border-collapse:collapse}td{padding:3px 0;border-bottom:1px dashed #999;vertical-align:top}td:last-child{text-align:right}.total{font-size:13px;font-weight:bold}.cut{border-top:1px dashed #000;margin:8px 0}</style></head><body><div class="c"><h2>${escapeHTML(s.header||'AYA GROUP')}</h2><p>${escapeHTML(s.address||sale.branchName||'')}</p><p>${escapeHTML(s.phone||'')}</p></div><div class="cut"></div><p>No: ${escapeHTML(sale.invoice)}</p><p>Kasir: ${escapeHTML(sale.cashierName||'-')}</p><p>${new Date(sale.createdAt).toLocaleString('id-ID')}</p><table>${rows}<tr><td>Subtotal</td><td>${rupiah(sale.subtotal)}</td></tr><tr><td>Ongkir</td><td>${rupiah(sale.shipping)}</td></tr><tr><td>Styrofoam</td><td>${rupiah(sale.styrofoamTotal)}</td></tr><tr><td>Diskon</td><td>-${rupiah(sale.discount)}</td></tr><tr class="total"><td>TOTAL</td><td>${rupiah(sale.total)}</td></tr><tr><td>Bayar</td><td>${rupiah(sale.paid)}</td></tr><tr><td>Kembali</td><td>${rupiah(sale.change)}</td></tr></table><p>Metode: ${escapeHTML(sale.paymentMethod)}</p><p>Pesanan: ${escapeHTML(sale.orderType)}</p><div class="cut"></div><div class="c"><p>${escapeHTML(s.footer||'Terima kasih')}</p></div><script>onload=()=>setTimeout(()=>print(),200)</script></body></html>`;
}
export function printReceipt(sale){const w=window.open('','_blank','width=420,height=720');if(!w)throw new Error('Pop-up diblokir browser. Izinkan pop-up untuk mencetak.');w.document.write(receiptHTML(sale));w.document.close()}
export function printLabel(product,{copies=1}={}){const labels=Array.from({length:copies},()=>`<div class="label"><b>${escapeHTML(product.name)}</b><strong>${rupiah(product.price)}</strong><small>${escapeHTML(product.barcode||product.id)}</small></div>`).join('');const w=window.open('','_blank');w.document.write(`<style>@page{margin:4mm}.label{display:inline-grid;width:45mm;height:28mm;border:1px solid #000;padding:3mm;margin:1mm;font:12px Arial}.label strong{font-size:18px}.label small{margin-top:auto}</style>${labels}<script>onload=()=>print()</script>`);w.document.close()}
export function printPage(){window.print()}
export function exportJSON(name,data){download(`${name}-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(data,null,2))}
